package com.Employee;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.Date;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import com.toedter.calendar.JDateChooser;

public class AddEmployee extends JPanel 
{
	private static final long serialVersionUID = 1L;
	JPanel panelNorth = new JPanel();
	JPanel panelCenter = new JPanel();
	JPanel panelNorthNorth = new JPanel();
	JPanel panelNorthNorthWest = new JPanel();
	JPanel panelNorthNorthCenter = new JPanel();
	JPanel panelNorthCenter = new JPanel();

	JLabel lblEmployeeId = new JLabel("Employee ID");
	JLabel lblEmployeeName = new JLabel("Employee Name");
	JLabel lblFathersName = new JLabel("Father's Name");
	JLabel lblGender = new JLabel("Gender");
	JLabel lblDesignation = new JLabel("Designation");
	JLabel lblQualification = new JLabel("Qualification");
	JLabel lblExperience = new JLabel("Experience");
	JLabel lblTypeOfEmployee = new JLabel("Type Of Employee");
	JLabel lblGrade = new JLabel("Grade");
	JLabel lblCategoryOfEmployee = new JLabel("Category Of Employee");
	JLabel lblTypeOfStaff = new JLabel("Type Of Staff");
	JLabel lblBloodGroup = new JLabel("Blood Group");
	JLabel lblDateOfBirth = new JLabel("Date Of Birth");
	JLabel lblDateOfJoin = new JLabel("Date Of Join");
	JLabel lblReligion = new JLabel("Religion");
	JLabel lblMaritalStatus	= new JLabel("Marital Status");
	JLabel lblNationality = new JLabel("Nationality");
	JLabel lblMedicalFitness = new JLabel("Medical Fitness");
	JLabel lblDocuments = new JLabel("Documents");
	JLabel lblExtraCurriculam = new JLabel("Extra Curriculam");
	JLabel lblDescription = new JLabel("Description");
	JLabel lblPresentAddress = new JLabel("Present Address");
	JLabel lblParmanentAddress = new JLabel("Parmanent Address");
	JLabel lblMobileNumber = new JLabel("Mobile Number");
	JLabel lblEmailId = new JLabel("Email Address");
	JLabel lblVerificationCard = new JLabel("Verification Card");
	JLabel lblCardNumber = new JLabel("Card Number");
	JTextField txtEmployeeID = new JTextField(14);
	JTextField txtEmployeeName = new JTextField(14);
	JTextField txtFathersName = new JTextField(14);
	String g[] = {"","Male","Female","Others"};
	JComboBox<String> cmbGender = new JComboBox<String>(g);
	String d[] = {"","Developement Manager","HR Manager","Project Manager","Design Manager","Sr. Programmer","Developer","Programmer","Marketing Manager","Counsellor","Office Boy"};
	JComboBox<String> cmbDesignation = new JComboBox<String>(d);
	String q[] = {"","ME","BE","BSC","MSC","MBA"};
	JComboBox<String> cmbQualification = new JComboBox<String>(q);
	String exp[] = {"","0 to 1 years","1 to 2 years","2 to 3 years","3 to 4 years","4 to 5 years","Above 5 years"};
	JComboBox<String> cmbExperience = new JComboBox<String>(exp);
	String t[] = {"","Full Time","Part Time","Casual","Fixed term","Shiftworkers","Daily Hire","Weekly Hire","Probation","Outworkers"};
	JComboBox<String> cmbTypeOfEmployee = new JComboBox<String>(t);
	JTextField txtGrade = new JTextField(14);
	String c[] = {"",""};
	JComboBox<String> cmbCategoryOfEmployee = new JComboBox<String>();
	JTextField txtTypeOfStaff = new JTextField();
	JComboBox<String> cmbBloodGroup = new JComboBox<String>();
	JDateChooser jdcDateOfBirth = new JDateChooser();
	JDateChooser jdcDateOfJoin = new JDateChooser();
	JComboBox<String> cmbReligion = new JComboBox<String>();
	String s[] = {"","Married","Single","Divorced","Seperated"};
	JComboBox<String> cmbMaritalStatus = new JComboBox<String>(s);
	JTextField txtNationality = new JTextField(14);
	String ara2[] = {"","Yes","No"};
	JComboBox<String> cmbMedicalFitness = new JComboBox<String>(ara2);
	JTextArea txtDocuments = new JTextArea();
	JScrollPane scrollDocuments = new JScrollPane(txtDocuments,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
	String ara3[] = {"","Yes","No"};
	JComboBox<String> cmbExtraCurriculam = new JComboBox<>(ara3);
	JTextArea txtDescription = new JTextArea();
	JScrollPane scrollDescription = new JScrollPane(txtDescription, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
	JTextArea txtPresentAddress = new JTextArea();
	JScrollPane scrollPresent = new JScrollPane(txtPresentAddress,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
	JTextArea txtParmanentAddress = new JTextArea();
	JScrollPane scrollParmanent = new JScrollPane(txtParmanentAddress,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
	JTextField txtMobile = new JTextField(14);
	JTextField txtEmail = new JTextField(14);
	JComboBox<String> cmbVerificationCard = new JComboBox<String>();
	JTextField txtCardNumber = new JTextField(14);
	JLabel lblUpload = new JLabel();
	JButton btnUpload = new JButton("Upload",new ImageIcon("icon/Upload.png"));
	JButton btnSave = new JButton(" Save   ", new ImageIcon("icon/Save.png"));
	JButton btnEdit = new JButton(" Edit    ", new ImageIcon("icon/Edit.png"));
	JButton btnRefresh = new JButton("Refresh ", new ImageIcon("icon/Refresh.png"));
	JButton btnDelete = new JButton("Delete ", new ImageIcon("icon/Delete.png"));
	
	
	ImageIcon uploadImage = new ImageIcon("icon/UploadImage.png");

	public AddEmployee()
	{
		init();
		cmp();
		lblUpload.setIcon(uploadImage);
	}
	private void cmp() 
	{
		BorderLayout border = new BorderLayout();
		border.setVgap(0);
		setLayout(border);
		add(panelNorth, BorderLayout.NORTH);
		panelNorthWork();
		add(panelCenter, BorderLayout.CENTER);
		panelCenterWork();
	}
	@SuppressWarnings("static-access")
	private void panelNorthWork() 
	{
		panelNorth.setBackground(Color.decode("#00CED1"));
		panelNorth.setPreferredSize(new Dimension(1, 455));
		TitledBorder titleEmployee = new TitledBorder("Employee Registration");
		titleEmployee.setTitleFont(new Font("Agency FB", Font.PLAIN+Font.BOLD, 20));
		titleEmployee.setTitleJustification(TitledBorder.LEFT);
		titleEmployee.setTitlePosition(titleEmployee.TOP);
		panelNorth.setBorder(titleEmployee);
		panelNorth.setLayout(new BorderLayout());
		panelNorth.add(panelNorthNorth, BorderLayout.NORTH);
		panelNorthNorthWork();
		panelNorth.add(panelNorthCenter, BorderLayout.CENTER);
		panelNorthCenterWork();
	}
	private void panelNorthNorthWork() 
	{
		panelNorthNorth.setPreferredSize(new Dimension(1, 370));
		panelNorthNorth.setBackground(Color.WHITE);
		panelNorthNorth.setLayout(new BorderLayout());
		panelNorthNorth.add(panelNorthNorthWest,BorderLayout.WEST);
		panelNorthNorthWestWork();
		panelNorthNorth.add(panelNorthNorthCenter, BorderLayout.CENTER);
		panelNorthNorthCenterWork();
	}
	private void panelNorthNorthWestWork() 
	{
		panelNorthNorthWest.setBackground(Color.WHITE);
		panelNorthNorthWest.setPreferredSize(new Dimension(935, 1));
		panelNorthNorthWest.setLayout(new GridBagLayout());
		GridBagConstraints c = new GridBagConstraints();
		c.fill = GridBagConstraints.BOTH;
		c.insets = new Insets(15, 10, 5, 5);
		c.gridx = 0;
		c.gridy = 0;
		panelNorthNorthWest.add(lblEmployeeId,c);
		lblEmployeeId.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(15, 2, 5, 5);
		c.gridx = 1;
		c.gridy = 0;
		panelNorthNorthWest.add(txtEmployeeID,c);
		c.insets = new Insets(15, 5, 5, 5);
		c.gridx = 2;
		c.gridy = 0;
		panelNorthNorthWest.add(lblEmployeeName,c);
		lblEmployeeName.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(15, 2, 5, 5);
		c.gridx = 3;
		c.gridy = 0;
		panelNorthNorthWest.add(txtEmployeeName,c);
		c.insets = new Insets(15, 5, 5, 5);
		c.gridx = 4;
		c.gridy = 0;
		panelNorthNorthWest.add(lblFathersName,c);
		lblFathersName.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(15, 2, 5, 5);
		c.gridx = 5;
		c.gridy = 0;
		panelNorthNorthWest.add(txtFathersName,c);
		c.insets = new Insets(5, 10, 5, 5);
		c.gridx = 0;
		c.gridy = 1;
		panelNorthNorthWest.add(lblGender,c);
		lblGender.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 1;
		c.gridy = 1;
		panelNorthNorthWest.add(cmbGender,c);
		cmbGender.setBackground(Color.white);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 2;
		c.gridy = 1;
		panelNorthNorthWest.add(lblDesignation,c);
		lblDesignation.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 3;
		c.gridy = 1;
		panelNorthNorthWest.add(cmbDesignation,c);
		cmbDesignation.setBackground(Color.white);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 4;
		c.gridy = 1;
		panelNorthNorthWest.add(lblQualification,c);
		lblQualification.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 5;
		c.gridy = 1;
		panelNorthNorthWest.add(cmbQualification,c);
		cmbQualification.setBackground(Color.white);
		c.insets = new Insets(5, 10, 5, 5);
		c.gridx = 0;
		c.gridy = 2;
		panelNorthNorthWest.add(lblExperience,c);
		lblExperience.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 1;
		c.gridy = 2;
		panelNorthNorthWest.add(cmbExperience,c);
		cmbExperience.setBackground(Color.white);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 2;
		c.gridy = 2;
		panelNorthNorthWest.add(lblTypeOfEmployee,c);
		lblTypeOfEmployee.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 3;
		c.gridy = 2;
		panelNorthNorthWest.add(cmbTypeOfEmployee,c);
		cmbTypeOfEmployee.setBackground(Color.white);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 4;
		c.gridy = 2;
		panelNorthNorthWest.add(lblGrade,c);
		lblGrade.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 5;
		c.gridy = 2;
		panelNorthNorthWest.add(txtGrade,c);
		c.insets = new Insets(5, 10, 5, 5);
		c.gridx = 0;
		c.gridy = 3;
		panelNorthNorthWest.add(lblCategoryOfEmployee,c);
		lblCategoryOfEmployee.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 1;
		c.gridy = 3;
		panelNorthNorthWest.add(cmbCategoryOfEmployee,c);
		cmbCategoryOfEmployee.setBackground(Color.white);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 2;
		c.gridy = 3;
		panelNorthNorthWest.add(lblTypeOfStaff,c);
		lblTypeOfStaff.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 3;
		c.gridy = 3;
		panelNorthNorthWest.add(txtTypeOfStaff,c);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 4;
		c.gridy = 3;
		panelNorthNorthWest.add(lblBloodGroup,c);
		lblBloodGroup.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 5;
		c.gridy = 3;
		panelNorthNorthWest.add(cmbBloodGroup,c);
		cmbBloodGroup.setBackground(Color.white);
		c.insets = new Insets(5, 10, 5, 5);
		c.gridx = 0;
		c.gridy = 4;
		panelNorthNorthWest.add(lblDateOfBirth,c);
		lblDateOfBirth.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 1;
		c.gridy = 4;
		panelNorthNorthWest.add(jdcDateOfBirth,c);
		jdcDateOfBirth.setBackground(Color.white);
		jdcDateOfBirth.setDateFormatString("dd-MM-yyyy");
		jdcDateOfBirth.setDate(new Date());
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 2;
		c.gridy = 4;
		panelNorthNorthWest.add(lblDateOfJoin,c);
		lblDateOfJoin.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 3;
		c.gridy = 4;
		panelNorthNorthWest.add(jdcDateOfJoin,c);
		jdcDateOfJoin.setBackground(Color.white);
		jdcDateOfJoin.setDateFormatString("dd-MM-yyyy");
		jdcDateOfJoin.setDate(new Date());
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 4;
		c.gridy = 4;
		panelNorthNorthWest.add(lblReligion,c);
		lblReligion.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 5;
		c.gridy = 4;
		panelNorthNorthWest.add(cmbReligion,c);
		cmbReligion.setBackground(Color.white);
		c.insets = new Insets(5, 10, 5, 5);
		c.gridx = 0;
		c.gridy = 5;
		panelNorthNorthWest.add(lblMaritalStatus,c);
		lblMaritalStatus.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 1;
		c.gridy = 5;
		panelNorthNorthWest.add(cmbMaritalStatus,c);
		cmbMaritalStatus.setBackground(Color.white);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 2;
		c.gridy = 5;
		panelNorthNorthWest.add(lblNationality,c);
		lblNationality.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 3;
		c.gridy = 5;
		panelNorthNorthWest.add(txtNationality,c);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 4;
		c.gridy = 5;
		panelNorthNorthWest.add(lblMedicalFitness,c);
		lblMedicalFitness.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 5;
		c.gridy = 5;
		panelNorthNorthWest.add(cmbMedicalFitness,c);
		cmbMedicalFitness.setBackground(Color.white);
		c.insets = new Insets(5, 10, 5, 5);
		c.gridx = 0;
		c.gridy = 6;
		panelNorthNorthWest.add(lblDocuments,c);
		lblDocuments.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 1;
		c.gridy = 6;
		panelNorthNorthWest.add(scrollDocuments,c);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 2;
		c.gridy = 6;
		panelNorthNorthWest.add(lblExtraCurriculam,c);
		lblExtraCurriculam.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 3;
		c.gridy = 6;
		panelNorthNorthWest.add(cmbExtraCurriculam, c);
		cmbExtraCurriculam.setBackground(Color.white);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 4;
		c.gridy = 6;
		panelNorthNorthWest.add(lblDescription,c);
		lblDescription.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 5;
		c.gridy = 6;
		panelNorthNorthWest.add(scrollDescription, c);
		c.insets = new Insets(5, 10, 5, 5);
		c.gridx = 0;
		c.gridy = 7;
		panelNorthNorthWest.add(lblPresentAddress,c);
		lblPresentAddress.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 1;
		c.gridy = 7;
		panelNorthNorthWest.add(scrollPresent, c);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 2;
		c.gridy = 7;
		panelNorthNorthWest.add(lblParmanentAddress,c);
		lblParmanentAddress.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 3;
		c.gridy = 7;
		panelNorthNorthWest.add(scrollParmanent, c);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 4;
		c.gridy = 7;
		panelNorthNorthWest.add(lblMobileNumber,c);
		lblMobileNumber.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 5;
		c.gridy = 7;
		panelNorthNorthWest.add(txtMobile, c);
		c.insets = new Insets(5, 10, 5, 5);
		c.gridx = 0;
		c.gridy = 8;
		panelNorthNorthWest.add(lblEmailId,c);
		lblEmailId.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 1;
		c.gridy = 8;
		panelNorthNorthWest.add(txtEmail, c);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 2;
		c.gridy = 8;
		panelNorthNorthWest.add(lblVerificationCard,c);
		lblVerificationCard.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 3;
		c.gridy = 8;
		panelNorthNorthWest.add(cmbVerificationCard, c);
		cmbVerificationCard.setBackground(Color.white);
		c.insets = new Insets(5, 5, 5, 5);
		c.gridx = 4;
		c.gridy = 8;
		panelNorthNorthWest.add(lblCardNumber,c);
		lblCardNumber.setFont(new Font("Times New Roman", Font.PLAIN+Font.BOLD, 14));
		c.insets = new Insets(5, 2, 5, 5);
		c.gridx = 5;
		c.gridy = 8;
		panelNorthNorthWest.add(txtCardNumber, c);
	}
	private void panelNorthNorthCenterWork() 
	{
		panelNorthNorthCenter.setBackground(Color.WHITE);
		panelNorthNorthCenter.setLayout(new GridBagLayout());
		GridBagConstraints c = new GridBagConstraints();
		c.fill = GridBagConstraints.BOTH;
		c.insets = new Insets(5, 5, 5, 10);
		c.gridx = 0;
		c.gridy = 0;
		panelNorthNorthCenter.add(lblUpload, c);
		lblUpload.setPreferredSize(new Dimension(130, 160));
		lblUpload.setBorder(BorderFactory.createLineBorder(Color.BLACK));
		c.insets = new Insets(15, 20, 110, 25);
		c.gridx = 0;
		c.gridy = 1;
		panelNorthNorthCenter.add(btnUpload, c);
		btnUpload.setBackground(Color.decode("#00CED1"));
		btnUpload.setFont(new Font("Arial Narrow",Font.PLAIN+Font.BOLD,15));
	}
	private void panelNorthCenterWork() 
	{
		panelNorthCenter.setBackground(Color.WHITE);
		panelNorthCenter.setLayout(new GridBagLayout());
		GridBagConstraints c = new GridBagConstraints();
		c.fill = GridBagConstraints.BOTH;
		c.insets = new Insets(5, 5, 7, 5);
		c.gridx = 0;
		c.gridy = 0;
		panelNorthCenter.add(btnSave,c);
		btnSave.setBackground(Color.decode("#00CED1"));
		btnSave.setFont(new Font("Arial",Font.PLAIN+Font.BOLD,13));
		c.insets = new Insets(5, 10, 7, 5);
		c.gridx = 1;
		c.gridy = 0;
		panelNorthCenter.add(btnEdit,c);
		btnEdit.setBackground(Color.decode("#00CED1"));
		btnEdit.setFont(new Font("Arial",Font.PLAIN+Font.BOLD,13));
		c.insets = new Insets(5, 10, 7, 5);
		c.gridx = 2;
		c.gridy = 0;
		panelNorthCenter.add(btnRefresh,c);
		btnRefresh.setBackground(Color.decode("#00CED1"));
		btnRefresh.setFont(new Font("Arial",Font.PLAIN+Font.BOLD,13));
		c.insets = new Insets(5, 10, 7, 5);
		c.gridx = 3;
		c.gridy = 0;
		panelNorthCenter.add(btnDelete,c);
		btnDelete.setBackground(Color.decode("#00CED1"));
		btnDelete.setFont(new Font("Arial",Font.PLAIN+Font.BOLD,13));
	}
	private void panelCenterWork() 
	{
		panelCenter.setBackground(Color.WHITE);
		
	}
	private void init() 
	{
		setPreferredSize(new Dimension(1105, 610));
		BorderLayout border = new BorderLayout();
		border.setHgap(0);
		setLayout(border);
		setVisible(true);
	}
}